version: '3.8'
services:             
    cosc304-mysql:
        image: mysql:8.0
        container_name: ss_proj
        restart: always
        environment:
            MYSQL_DATABASE: 'ss'
            MYSQL_USER: 'ss'
            MYSQL_PASSWORD: 'ssproj'            
            MYSQL_ROOT_PASSWORD: 'ssproj'
        ports:
            - '3306:3306'
        expose:
            - '3306'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
volumes:     
    mysql-db: